### ISSUE TITLE
Green Thumb error on spigot 1.11.2

### ISSUE THREAD

**Issue by DankPrison** [Zedly/Zenchantments#14]
When players are standing near netherwarts with green thumb enchant it triggers this error

[06:30:25 WARN]: [Zenchantments] Task #799 for Zenchantments v1.5.0-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 7 on block minecraft:nether_wart, it is not an allowed value
	at net.minecraft.server.v1_11_R1.BlockStateList$BlockData.set(SourceFile:184) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.BlockNetherWart.fromLegacyData(BlockNetherWart.java:72) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.setData(CraftBlock.java:105) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.setData(CraftBlock.java:90) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at zedly.zenchantments.compatibility.CompatibilityAdapter.placeBlock(CompatibilityAdapter.java:133) ~[?:?]
	at zedly.zenchantments.compatibility.CompatibilityAdapter.grow(CompatibilityAdapter.java:305) ~[?:?]
	at zedly.zenchantments.CustomEnchantment$GreenThumb.onScan(CustomEnchantment.java:1180) ~[?:?]
	at zedly.zenchantments.MFEffects.scanPlayers(MFEffects.java:66) ~[?:?]
	at zedly.zenchantments.MFEffects.run(MFEffects.java:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Zedly** [comment]
This should be fixed in the latest commit. Please tell me if it is still borken :)
