### ISSUE TITLE
Problem/warning when shot with Burst II

### ISSUE THREAD

**Issue by scorninpc** [Zedly/Zenchantments#34]
This warning appear when we shot. Every arrow dispach an warning.

How can I help more? what more information can I provide?

```WARNING] .... [Zenchantments] Task #734 for Zenchantments v1.6.2 generated an exception

java.lang.NoSuchMethodError: org/bukkit/event/entity/EntityShootBowEvent.<init>(Lorg/bukkit/entity/LivingEntity;Lorg/bukkit/inventory/ItemStack;Lorg/bukkit/entity/Projectile;F)V (loaded from file:/home/gs-40763/cache/patched_1.14.4.jar by sun.misc.Launcher$AppClassLoader@783a8847) called from class zedly.zenchantments.enchantments.Burst (loaded from file:/home/gs-40763/plugins/Zenchantments%20v1.6.2.jar by org.bukkit.plugin.java.PluginClassLoader@406ebb1f).

at zedly.zenchantments.enchantments.Burst.lambda$onBlockInteract$53(Burst.java:62) ~[?:?]

at zedly.zenchantments.enchantments.Burst$$Lambda$3716.0000000061812FF0.run(Unknown Source) ~[?:?]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]```

**Comment by Zedly** [comment]
Hello Bruno, thank you for reaching out! The new build of Zenchantments
fixes some problems with Burst.
Head over to https://dev.bukkit.org/projects/zenchantments to download the
latest jar and let me know if that fixes it :)

-brain

**Comment by scorninpc** [comment]
O man, i'v downloaded from spigotmc. I'll download the last release. thank you and sorry =)
