### ISSUE TITLE
Anvil bug

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [Zedly/Zenchantments#5]
When Repairing something in the anvil it does not give the correct repair value and when repairing this error is thrown

Could not pass event PlayerInteractEvent to Zenchantments v1.5.0-SNAPSHOT
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1375) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at zedly.zenchantments.CustomEnchantment$Spectral.onBlockInteract(CustomEnchantment.java:2618) ~[?:?]
at zedly.zenchantments.WatcherEnchant.onBlockInteract(WatcherEnchant.java:69) ~[?:?]
at sun.reflect.GeneratedMethodAccessor393.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
... 18 more

**Comment by xH3LLRAIZ3Rx** [comment]
Fixed in latest dev build
