### ISSUE TITLE
Can't pass event InventoryClickEvent

### ISSUE THREAD

**Issue by NotKasei** [Zedly/Zenchantments#51]
Sorry to bother, and sorry for my bad English.
I have a issue, just like title, it was Could not pass event InventoryClickEvent to Enchantments_plus v1.2.2
but I don't know how to fix it, I try to figure out what event cause this error but I failed, so ask you for help, this is server log:

[21:37:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Enchantments_plus v1.2.2
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_261]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_261]
	at de.geolykt.enchantments_plus.evt.GrindstoneMerge.onClicks(GrindstoneMerge.java:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor275.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-223]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-223]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-223]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-223]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-223]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

And another...issue?
That is, I try to set some enchant's probability, just like the annotation say, set 0 to no probability and set to -1 can disable it, but when I try to change it, plugin will not work(server can run, but can't enchant any new enchantment, all exsist enchantment of this plugin will not work, although it still on my tools and armors), is my setting go wrong?

thanks for your help.

**Comment by Geolykt** [comment]
This is the wrong repository (and an outdated version), please report it to https://github.com/Geolykt/EnchantmentsPlus/ , thanks

**Comment by NotKasei** [comment]
Oh shit........... I'm sorry, thanks!!
