### ISSUE TITLE
Zenchantments Latest Dev Branch build not loading

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [Zedly/Zenchantments#6]
It seems like the plugin doesn't want to load when there is no configs present

**Comment by xH3LLRAIZ3Rx** [comment]
here is the error:

java.lang.NullPointerException
at zedly.zenchantments.UpdateConfig.oneFourOne(UpdateConfig.java:71) ~[?:?]
at zedly.zenchantments.UpdateConfig.update(UpdateConfig.java:19) ~[?:?]
at zedly.zenchantments.Config.loadConfigs(Config.java:129) ~[?:?]
at zedly.zenchantments.Zenchantments.loadConfigs(Zenchantments.java:21) ~[?:?]
at zedly.zenchantments.Zenchantments.onEnable(Zenchantments.java:27) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by xH3LLRAIZ3Rx** [comment]
Its fixed when I changed the config version manually

**Comment by xH3LLRAIZ3Rx** [comment]
New error with latest dev build

java.lang.NullPointerException
at zedly.zenchantments.Config.loadConfigs(Config.java:97) ~[?:?] at zedly.zenchantments.Zenchantments.loadConfigs(Zenchantments.java:21) ~[?:?] at zedly.zenchantments.Zenchantments.onEnable(Zenchantments.java:27) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?] at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?] at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111] at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-aad97c4-4602331] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Zedly** [comment]
Config referenced JavaPlugin instance before it saved itself in Storage
