### ISSUE TITLE
Dev Branch Combust Error

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [Zedly/Zenchantments#8]
Getting this error

Could not pass event EntityCombustByEntityEvent to Zenchantments v1.5.0-SNAPSHOT
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1135) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1124) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1561) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftSheep cannot be cast to org.bukkit.entity.Player
at zedly.zenchantments.WatcherEnchant.onCombust(WatcherEnchant.java:259) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
... 17 more

**Comment by Zedly** [comment]
Added type check in a recent commit
